"""add_publication_contract_and_runs

Revision ID: 11ed027cca91
Revises: e04f3b756c75
Create Date: 2026-07-12 07:03:04.108415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ed027cca91'
down_revision: Union[str, Sequence[str], None] = 'e04f3b756c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_signal_count', sa.Integer(), nullable=False),
    sa.Column('created_candidate_count', sa.Integer(), nullable=False),
    sa.Column('updated_candidate_count', sa.Integer(), nullable=False),
    sa.Column('gate_passed_count', sa.Integer(), nullable=False),
    sa.Column('gate_rejected_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_public_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('old_public_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_public_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_public_id')
    )
    op.create_table('publishing_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('published_count', sa.Integer(), nullable=False),
    sa.Column('jurypress_ready_count', sa.Integer(), nullable=False),
    sa.Column('dataset_content_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('scored_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # 1. Add columns as nullable first
    with op.batch_alter_table('opportunities') as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('public_revision', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('public_content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_published_at', sa.DateTime(timezone=True), nullable=True))

    # 2. Backfill public_id and public_revision
    connection = op.get_bind()
    opportunities = connection.execute(sa.text("SELECT id FROM opportunities")).fetchall()
    for opp in opportunities:
        opp_id = opp[0]
        public_id = f"opp_{opp_id.replace('-', '')}"
        connection.execute(
            sa.text("UPDATE opportunities SET public_id = :public_id, public_revision = 1 WHERE id = :id"),
            {"public_id": public_id, "id": opp_id}
        )

    # 3. Make columns non-nullable and add constraints/indices
    with op.batch_alter_table('opportunities') as batch_op:
        batch_op.alter_column('public_id', nullable=False, existing_type=sa.String(length=64))
        batch_op.alter_column('public_revision', nullable=False, existing_type=sa.Integer())
        batch_op.create_index('idx_opportunities_public_id', ['public_id'], unique=False)
        batch_op.create_unique_constraint('uq_opportunities_public_id', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities') as batch_op:
        batch_op.drop_constraint('uq_opportunities_public_id', type_='unique')
        batch_op.drop_index('idx_opportunities_public_id')
        batch_op.drop_column('last_published_at')
        batch_op.drop_column('first_published_at')
        batch_op.drop_column('public_content_hash')
        batch_op.drop_column('public_revision')
        batch_op.drop_column('public_id')

    op.drop_table('scoring_runs')
    op.drop_table('publishing_runs')
    op.drop_table('opportunity_public_aliases')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
