"""add_discovery_models_and_signal_columns

Revision ID: 74de87b89dff
Revises: 14bea315aff7
Create Date: 2026-07-13 06:18:26.635124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74de87b89dff'
down_revision: Union[str, Sequence[str], None] = '14bea315aff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manifest_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manifest_date')
    )
    op.create_table('discovery_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('first_discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('dispatch_status', sa.String(length=50), nullable=False),
    sa.Column('resolved_signal_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_url')
    )
    op.create_table('discovery_lead_occurrences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('raw_title', sa.String(length=512), nullable=True),
    sa.Column('raw_context', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['discovery_leads.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['discovery_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('signals', sa.Column('document_kind', sa.Enum('STANDALONE_DEMAND', 'GENERATED_DIGEST', 'REPOST', 'UNKNOWN', name='signaldocumentkind', native_enum=False), nullable=False, server_default='UNKNOWN'))
    op.add_column('signals', sa.Column('opportunity_anchor', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('signals', sa.Column('discovery_eligible', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('signals', sa.Column('source_specificity', sa.Enum('low', 'medium', 'high', 'unknown', name='sourcespecificity', native_enum=False), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'source_specificity')
    op.drop_column('signals', 'discovery_eligible')
    op.drop_column('signals', 'opportunity_anchor')
    op.drop_column('signals', 'document_kind')
    op.drop_table('discovery_lead_occurrences')
    op.drop_table('discovery_leads')
    op.drop_table('discovery_reports')
    # ### end Alembic commands ###
