"""add_generalizability_to_opportunity

Revision ID: 7d59025ee7ba
Revises: 74de87b89dff
Create Date: 2026-07-13 06:26:56.935075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d59025ee7ba'
down_revision: Union[str, Sequence[str], None] = '74de87b89dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('generalizability', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'generalizability')
    # ### end Alembic commands ###
