"""add_scheduler_tables

Revision ID: b68c7eff7f71
Revises: e3a24bdd14a1
Create Date: 2026-07-11 10:05:07.550260

WARNING: Downgrading this migration will delete the `schedule_executions`,
`scheduler_leases`, and `source_schedules` tables. All schedule configurations
and scheduler execution history will be permanently lost.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68c7eff7f71'
down_revision: Union[str, Sequence[str], None] = 'e3a24bdd14a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_leases',
    sa.Column('lease_name', sa.String(length=50), nullable=False),
    sa.Column('owner_token', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at >= heartbeat_at AND heartbeat_at >= acquired_at', name='chk_scheduler_leases_timestamps'),
    sa.PrimaryKeyConstraint('lease_name')
    )
    op.create_table('source_schedules',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('interval_minutes >= 5 AND interval_minutes <= 525600', name='chk_source_schedules_interval_minutes'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index('idx_source_schedules_enabled_next_run', 'source_schedules', ['enabled', 'next_run_at'], unique=False)
    op.create_index('idx_source_schedules_next_run', 'source_schedules', ['next_run_at'], unique=False)
    op.create_table('schedule_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('collection_run_id', sa.String(length=36), nullable=True),
    sa.Column('coalesced_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'partial', 'failed', 'skipped_busy', 'skipped_disabled', 'abandoned')", name='chk_schedule_executions_status_allowed'),
    sa.CheckConstraint('coalesced_count >= 0', name='chk_schedule_executions_coalesced_nonnegative'),
    sa.ForeignKeyConstraint(['collection_run_id'], ['collection_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_run_id'),
    sa.UniqueConstraint('source_id', 'scheduled_for', name='uq_schedule_executions_source_scheduled')
    )
    op.create_index('idx_schedule_executions_scheduled_for', 'schedule_executions', ['scheduled_for'], unique=False)
    op.create_index('idx_schedule_executions_source_scheduled', 'schedule_executions', ['source_id', 'scheduled_for'], unique=False)
    op.create_index('idx_schedule_executions_status_started', 'schedule_executions', ['status', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema. WARNING: This will drop tables and cause permanent data loss for schedules and history."""
    # 1. schedule_executions
    op.drop_index('idx_schedule_executions_status_started', table_name='schedule_executions')
    op.drop_index('idx_schedule_executions_source_scheduled', table_name='schedule_executions')
    op.drop_index('idx_schedule_executions_scheduled_for', table_name='schedule_executions')
    op.drop_table('schedule_executions')

    # 2. scheduler_leases
    op.drop_table('scheduler_leases')

    # 3. source_schedules
    op.drop_index('idx_source_schedules_next_run', table_name='source_schedules')
    op.drop_index('idx_source_schedules_enabled_next_run', table_name='source_schedules')
    op.drop_table('source_schedules')
    # ### end Alembic commands ###
