"""create_initial_schema

Revision ID: cced3ad721f1
Revises:
Create Date: 2026-07-06 02:28:03.974839

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cced3ad721f1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=True),
        sa.Column("target_user", sa.Text(), nullable=True),
        sa.Column("proposed_solution", sa.Text(), nullable=True),
        sa.Column("existing_projects", sa.Text(), nullable=True),
        sa.Column("remaining_gap", sa.Text(), nullable=True),
        sa.Column("mvp_scope", sa.Text(), nullable=True),
        sa.Column("monetization_hypothesis", sa.Text(), nullable=True),
        sa.Column("distribution_hypothesis", sa.Text(), nullable=True),
        sa.Column("validation_method", sa.Text(), nullable=True),
        sa.Column("evidence_score", sa.Integer(), nullable=False),
        sa.Column("feasibility_score", sa.Integer(), nullable=False),
        sa.Column("penalty_score", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum("low", "medium", "high", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "inbox",
                "watch",
                "validate",
                "build",
                "rejected",
                "archived",
                name="opportunitystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "evidence_score >= 0 AND evidence_score <= 50",
            name="chk_opportunities_evidence_score_range",
        ),
        sa.CheckConstraint(
            "feasibility_score >= 0 AND feasibility_score <= 50",
            name="chk_opportunities_feasibility_score_range",
        ),
        sa.CheckConstraint(
            "penalty_score <= 0", name="chk_opportunities_penalty_score_range"
        ),
        sa.CheckConstraint(
            "total_score >= 0 AND total_score <= 100",
            name="chk_opportunities_total_score_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_opportunities_confidence", "opportunities", ["confidence"], unique=False
    )
    op.create_index(
        "idx_opportunities_created_at", "opportunities", ["created_at"], unique=False
    )
    op.create_index(
        "idx_opportunities_status", "opportunities", ["status"], unique=False
    )
    op.create_index(
        "idx_opportunities_total_score", "opportunities", ["total_score"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=1024), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auth_required", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "collection_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "partial",
                "failed",
                name="collectionrunstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_count", sa.Integer(), nullable=False),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("run_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "duplicate_count >= 0", name="chk_runs_duplicate_count_nonnegative"
        ),
        sa.CheckConstraint("error_count >= 0", name="chk_runs_error_count_nonnegative"),
        sa.CheckConstraint(
            "fetched_count >= 0", name="chk_runs_fetched_count_nonnegative"
        ),
        sa.CheckConstraint(
            "inserted_count >= 0", name="chk_runs_inserted_count_nonnegative"
        ),
        sa.CheckConstraint(
            "updated_count >= 0", name="chk_runs_updated_count_nonnegative"
        ),
        sa.CheckConstraint(
            "warning_count >= 0", name="chk_runs_warning_count_nonnegative"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "inbox",
                "watch",
                "validate",
                "build",
                "rejected",
                "archived",
                name="opportunitystatus",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "inbox",
                "watch",
                "validate",
                "build",
                "rejected",
                "archived",
                name="opportunitystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_decisions_opp_created",
        "decisions",
        ["opportunity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(body)) > 0", name="chk_notes_body_nonempty"),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "score_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_score", sa.Integer(), nullable=False),
        sa.Column("feasibility_score", sa.Integer(), nullable=False),
        sa.Column("penalty_score", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum("low", "medium", "high", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("scoring_version", sa.String(length=50), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_score_snapshots_opp_created",
        "score_snapshots",
        ["opportunity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("collection_run_id", sa.String(length=36), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("canonical_url", sa.String(length=1024), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column(
            "signal_type",
            sa.Enum(
                "project",
                "pain",
                "request",
                "adoption",
                "launch",
                "hackathon_project",
                "funding",
                "job_demand",
                "trend",
                "comparison",
                "migration",
                "complaint",
                "manual",
                name="signaltype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("freshness_score", sa.Float(), nullable=False),
        sa.Column("source_quality_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "freshness_score >= 0.0 AND freshness_score <= 1.0",
            name="chk_signals_freshness_score_range",
        ),
        sa.CheckConstraint(
            "source_quality_score >= 0.0 AND source_quality_score <= 1.0",
            name="chk_signals_source_quality_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_signals_canonical_url", "signals", ["canonical_url"], unique=False
    )
    op.create_index(
        "idx_signals_collection_run_id", "signals", ["collection_run_id"], unique=False
    )
    op.create_index(
        "idx_signals_content_hash", "signals", ["content_hash"], unique=False
    )
    op.create_index(
        "idx_signals_published_at", "signals", ["published_at"], unique=False
    )
    op.create_index("idx_signals_signal_type", "signals", ["signal_type"], unique=False)
    op.create_index(
        "idx_signals_source_external",
        "signals",
        ["source_id", "external_id"],
        unique=True,
        sqlite_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_index("idx_signals_source_id", "signals", ["source_id"], unique=False)
    op.create_table(
        "opportunity_signals",
        sa.Column("opportunity_id", sa.String(length=36), nullable=False),
        sa.Column("signal_id", sa.String(length=36), nullable=False),
        sa.Column(
            "relation_type",
            sa.Enum(
                "supporting",
                "contradicting",
                "related",
                name="evidencerelationtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relevance_score >= 0.0 AND relevance_score <= 1.0",
            name="chk_opp_signals_relevance_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("opportunity_id", "signal_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunity_signals")
    op.drop_index("idx_signals_source_id", table_name="signals")
    op.drop_index(
        "idx_signals_source_external",
        table_name="signals",
        sqlite_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index("idx_signals_signal_type", table_name="signals")
    op.drop_index("idx_signals_published_at", table_name="signals")
    op.drop_index("idx_signals_content_hash", table_name="signals")
    op.drop_index("idx_signals_collection_run_id", table_name="signals")
    op.drop_index("idx_signals_canonical_url", table_name="signals")
    op.drop_table("signals")
    op.drop_index("idx_score_snapshots_opp_created", table_name="score_snapshots")
    op.drop_table("score_snapshots")
    op.drop_table("notes")
    op.drop_index("idx_decisions_opp_created", table_name="decisions")
    op.drop_table("decisions")
    op.drop_table("collection_runs")
    op.drop_table("sources")
    op.drop_index("idx_opportunities_total_score", table_name="opportunities")
    op.drop_index("idx_opportunities_status", table_name="opportunities")
    op.drop_index("idx_opportunities_created_at", table_name="opportunities")
    op.drop_index("idx_opportunities_confidence", table_name="opportunities")
    op.drop_table("opportunities")
    # ### end Alembic commands ###
