"""add_opportunity_enrichment_localizations

Revision ID: dddafacb2e7a
Revises: f9af7cf71708
Create Date: 2026-07-11 19:57:38.790420

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dddafacb2e7a"
down_revision: str | Sequence[str] | None = "f9af7cf71708"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunity_enrichment_localizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("enrichment_id", sa.String(length=36), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("generated_title", sa.String(length=100), nullable=True),
        sa.Column("generated_summary", sa.String(length=500), nullable=True),
        sa.Column("problem_statement", sa.String(length=500), nullable=True),
        sa.Column("target_users", sa.JSON(), nullable=False),
        sa.Column("why_now", sa.String(length=500), nullable=True),
        sa.Column("evidence_synthesis", sa.String(length=800), nullable=True),
        sa.Column("build_direction", sa.String(length=500), nullable=True),
        sa.Column("risks", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("locale IN ('en', 'ja')", name="chk_locale_allowed"),
        sa.ForeignKeyConstraint(
            ["enrichment_id"], ["opportunity_enrichments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enrichment_id", "locale", name="uq_enrichment_locale"),
    )
    op.create_index(
        "idx_enrichment_localizations_enrich_id",
        "opportunity_enrichment_localizations",
        ["enrichment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_enrichment_localizations_enrich_id",
        table_name="opportunity_enrichment_localizations",
    )
    op.drop_table("opportunity_enrichment_localizations")
    # ### end Alembic commands ###
