"""add_gate_fields

Revision ID: e04f3b756c75
Revises: 83bcf9995780
Create Date: 2026-07-12 05:56:39.189423

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e04f3b756c75"
down_revision: str | Sequence[str] | None = "83bcf9995780"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "opportunities", sa.Column("gate_version", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "opportunities", sa.Column("gate_status", sa.String(length=50), nullable=True)
    )
    op.add_column("opportunities", sa.Column("gate_reason", sa.Text(), nullable=True))
    op.add_column(
        "opportunities",
        sa.Column("gate_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opportunities", "gate_checked_at")
    op.drop_column("opportunities", "gate_reason")
    op.drop_column("opportunities", "gate_status")
    op.drop_column("opportunities", "gate_version")
    # ### end Alembic commands ###
