"""add_opportunity_enrichments

Revision ID: f9af7cf71708
Revises: b68c7eff7f71
Create Date: 2026-07-11 19:43:32.298856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9af7cf71708'
down_revision: Union[str, Sequence[str], None] = 'b68c7eff7f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_enrichments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('model_revision', sa.String(length=100), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=False),
    sa.Column('runtime', sa.String(length=100), nullable=False),
    sa.Column('runtime_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_title', sa.String(length=100), nullable=True),
    sa.Column('generated_summary', sa.String(length=500), nullable=True),
    sa.Column('problem_statement', sa.String(length=500), nullable=True),
    sa.Column('target_users', sa.JSON(), nullable=False),
    sa.Column('why_now', sa.String(length=500), nullable=True),
    sa.Column('evidence_synthesis', sa.String(length=800), nullable=True),
    sa.Column('build_direction', sa.String(length=500), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('llm_confidence', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("error_code IN ('LLM_MODEL_DOWNLOAD_FAILED', 'LLM_MODEL_CHECKSUM_FAILED', 'LLM_RUNTIME_START_FAILED', 'LLM_TIMEOUT', 'LLM_INVALID_JSON', 'LLM_SCHEMA_VALIDATION_FAILED', 'LLM_INFERENCE_FAILED') OR error_code IS NULL", name='chk_opportunity_enrichments_error_code'),
    sa.CheckConstraint("llm_confidence IN ('low', 'medium', 'high') OR llm_confidence IS NULL", name='chk_opportunity_enrichments_confidence'),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed', 'invalid_output', 'skipped')", name='chk_opportunity_enrichments_status'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'model_id', 'model_revision', 'prompt_version', 'input_hash', name='uq_opportunity_enrichments_input')
    )
    op.create_index('idx_opportunity_enrichments_opp_id', 'opportunity_enrichments', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_opportunity_enrichments_opp_id', table_name='opportunity_enrichments')
    op.drop_table('opportunity_enrichments')
    # ### end Alembic commands ###
